### ISSUE TITLE
How to calculate oracle scores

### ISSUE THREAD

**Issue by hukuda222** [jiacheng-xu/DiscoBERT#5]
I tried to reproduce the Oracle (Discourse) score for CNN/DM in the paper, but it did not work.
In the paper, ROUGE-1 and ROUGE-2 are reported as 61.61 and 37.82, respectively, but when I calculated them, ROUGE-1 and ROUGE-2 were 55.10 and 32.22, respectively.
Could you please tell me more details on how to calculate this?

**Comment by jiacheng-xu** [comment]
Hi! What's your sentence oracle on CNN/DM? Oracle (discourse) should be strictly greater than the sentence counterpart. Also, what's your script/package for oracle evaluation?

**Comment by hukuda222** [comment]
I'm very sorry, I mistook Oracle (Sentence) for Oracle (Discourse). I was able to reproduce the score in the paper.

**Comment by chetanambi** [comment]
@hukuda222 Would you be able to provide steps to generate the summary?

**Comment by GuanNiPiShi123** [comment]
Run which script can obtain the ROUGE score ? @hukuda222 @jiacheng-xu
